CREATE OR REPLACE DATABASE kisuu;
USE kisuu;
CREATE TABLE 奇数 (
	値 INTEGER(10)
);
INSERT INTO 奇数 VALUES(1);
INSERT INTO 奇数 VALUES(3);
INSERT INTO 奇数 VALUES(5);
INSERT INTO 奇数 VALUES(7);
INSERT INTO 奇数 VALUES(9);
SHOW TABLES;
DESCRIBE 奇数;
SELECT * FROM 奇数;
